#!/usr/bin/env python

import sys,os
import getopt
import rtmext

if __name__ == '__main__':
    args=sys.argv
    
    opts,args = getopt.getopt(args[1:],"",["clean","nochain"])

    if len(args)==0:
        pack=os.path.basename(os.getcwd())
    elif len(args)==1:
        pack=args[0]
    else:
        print >>sys.stderr, "usage: rtmmake [package]"
        sys.exit(1)

    clean=False
    nochain=False
    for opt,val in opts:
        print opt
        if opt == "--clean":
            clean=True
        elif opt == "--nochain":
            nochain=True

    rtmext.rtmmake(pack,clean,nochain)
