#!/usr/bin/env python

import sys,os
import rtmext

if __name__ == '__main__':
    args=sys.argv
    if len(args)<2:
        print >>sys.stderr, "rtmpack: args too few."
        sys.exit(1)
    print rtmext.rtmpack(args[1:])
