#!/usr/bin/env python

import sys,os,subprocess,signal
import getopt
import rtmext

if __name__ == '__main__':
    args=sys.argv

    if len(args)!=3:
        print >>sys.stderr, "usage: rtmrun [package] [component]"
        sys.exit(1)

    cxt=rtmext.rtmrun(args[1],args[2])

    if cxt:
        try:
            while not cxt.poll():
                pass
        except KeyboardInterrupt:
            cxt.send_signal(signal.SIGINT)
            cxt.wait()
    else:
        print >>sys.stderr, "rtmrun failed: " + args[1] + " : " + args[2]
        exit(1)

    print "process terminated."
